#######################################################
# Starship Preferences
#######################################################

# Prompt
#######################################################

# Left prompt format
format = """
[ â•­â”€accountâ”€âœâ‡‰â¯>](bold blue) $username$sudo$time
[ â”£â”€systemâ”€â”€â”€âœâ‡‰â¯>](bold yellow) $shell$status$cmd_duration$jobs$docker_context$hostname$battery
[ â”£â”€projectâ”€â”€âœâ‡‰â¯>](bold red) $directory$git_branch$git_status
[ â•°â”€cmdâ”€âœâ‡‰â¯](bold green) $character
"""
# Right prompt format
right_format = """$lua$rust$java$kotlin$dart$python$golang$swift$nodejs$php$conda$package """

# Adds a new line after the prompt
add_newline = true
# Max time for the prompt commands to run in milliseconds
command_timeout = 800
# Max time for scaning files in the current directory in milliseconds
scan_timeout = 50

# System
####################################################################

[character]
disabled = false
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[V](bold blue)"
format = "$symbol "

[cmd_duration]
disabled = false
show_milliseconds = true
format = "took [$duration](bold yellow) "

[package]
disabled = false
format = "[ğŸ $version](208 bold) "

[shell]
disabled = false
fish_indicator = "ğŸ "
powershell_indicator = "ï‘ _"
unknown_indicator = "â“"
bash_indicator = "ğŸ‘"
zsh_indicator = "ğŸ¦“"
format = "shell:$indicator "

[directory]
disabled = false
truncation_length = 10
truncation_symbol = "â€¦/"
truncate_to_repo = false
home_symbol = "ğŸ¡"
style = "white"

[username]
disabled = false
style_user = "italic bright-purple"
style_root = "red bold"
format = "user:[$user]($style) "
show_always = true

[sudo]
disabled = false
style = "bold green"
symbol = "ğŸ§™"
format = "as $symbol "

[time]
disabled = false
format = 'at â°:[\[$time\]](bold yellow) '

[hostname]
disabled = false
ssh_only = false
format = 'on [$hostname](bold red) '
trim_at = "."

[status]
disabled = false
style = "red"
symbol = "ğŸ’¥ "
format = '[\[$symbol$status\]]($style) '

# Battery
[battery]
disabled = false
full_symbol = "ğŸ’ª"
unknown_symbol = "ğŸ’¡"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’¦"
format = "ğŸ”‹:$symbol "
[[battery.display]]
threshold = 100

#Jobs
[jobs]
disabled = false
format = "background [$symbol$number]($style) "

# Services
##############################################################################

[git_branch]
disabled = false
always_show_remote = true
symbol = "ğŸŒ± "
style = "bold blue"

[git_status]
disabled = false
ahead = "â‡¡ğŸğŸ’¨${count}"
diverged = "â‡•â‡¡ğŸ˜µ${ahead_count}â‡£${behind_count}"
behind = "â‡£ğŸ˜°${count}"
conflicted = "ğŸ¤º"
untracked = "ğŸ¤·"
modified = "ğŸ“"
stashed = "ğŸ“¦"
staged = '[++\($count\)](green)'
renamed = "ğŸ“›"
deleted = "ğŸš®"

[docker_context]
disabled = false

# To supress anaconda's own prompt moddifer, run,  conda config --set changeps1 False
[conda]
disabled = false
format = "in [$symbol$environment](dimmed green) "
ignore_base = true

# Programming Languages and Frameworks
#############################################################################
[lua]
disabled = false

[java]
disabled = false

[kotlin]
disabled = false

[dart]
disabled = false

[golang]
disabled = false

[nodejs]
disabled = false

[python]
disabled = false

[rust]
disabled = false

[swift]
disabled = false

[php]
disabled = false

